// Palabras que clasifican un gasto automáticamente al apuntarlo.
//
// CÓMO FUNCIONA: cuando alguien apunta un gasto sin elegir categoría, se mira el concepto
// (en minúsculas y sin tildes: "Súper" = "super") y se recorre esta lista DE ARRIBA A ABAJO;
// la PRIMERA regla que tenga una palabra contenida en el concepto decide la categoría.
// Si ninguna coincide, queda en «Otros».
//
// CÓMO EDITARLA: añade una palabra entre comillas a la categoría que quieras.
//   - Texto normal ("hotel")   → vale si el concepto CONTIENE esas letras ("hotel playa").
//   - "\\bsuper\\b"             → vale solo como PALABRA ENTERA (no en "superman").
//   - Si dos categorías compiten, gana la regla que esté más arriba.
//
// Alojamiento = solo la vivienda: renta/alquiler, hipoteca, hotel, Airbnb…
// Internet y telefonía NO son alojamiento: van en Compras.

export interface ReglaCategoria {
  categoria: string;
  palabras: string[];
}

export const REGLAS: ReglaCategoria[] = [
  {
    categoria: "Compras",
    palabras: [
      "mercado ?libre",
      "mercadolibre",
      "liverpool",
      "coppel",
      "elektra",
      "\\btemu\\b",
    ],
  },
  {
    categoria: "Alojamiento",
    palabras: [
      "\\bmantto\\b",
      "cuota de mantenimiento",
      "mantenimiento (de |del )?(edificio|casa|depa|departamento|condominio|fraccionamiento)",
      "predial",
      "\\bcfe\\b",
      "infonavit",
    ],
  },
  {
    categoria: "Transporte",
    palabras: [
      "pemex",
      "\\bcaseta\\b",
      "\\bcamion\\b",
      "metrobus",
      "\\bdidi\\b",
      "\\bcombi\\b",
      "\\btransporte\\b",
      "estacionamiento",
    ],
  },
  {
    categoria: "Comida",
    palabras: [
      "\\bsuper\\b",
      "tianguis",
      "\\bmercado\\b(?! ?(libre|pago))",
      "oxxo",
      "walmart",
      "soriana",
      "chedraui",
      "\\bheb\\b",
      "bodega aurrera",
      "costco",
      "sams club",
      "la comer",
      "tortiller",
      "abarrotes",
      "taqueria",
      "antojitos",
      "\\bcomidas?\\b",
      "\\bcomer\\b",
    ],
  },
  {
    categoria: "Caridad",
    palabras: [
      "donacion",
      "donativo",
      "caridad",
      "\\bong\\b",
      "cruz roja",
      "caritas",
      "unicef",
      "oxfam",
      "medicos sin fronteras",
      "greenpeace",
      "manos unidas",
      "diezmo",
      "ofrenda",
      "limosna",
      "crowdfunding solidario",
      "charity",
      "donation",
      "donate",
    ],
  },
  {
    categoria: "Salud",
    palabras: [
      "farmacia",
      "medico",
      "doctor",
      "dentista",
      "ortodoncia",
      "hospital",
      "clinica",
      "urgencias",
      "fisio",
      "psicolog",
      "terapia",
      "oculista",
      "optica",
      "gafas",
      "lentillas",
      "dermatolog",
      "podolog",
      "nutricionista",
      "analitica",
      "vacuna",
      "medicamento",
      "ibuprofeno",
      "paracetamol",
      "sanitas",
      "adeslas",
      "asisa",
      "dkv",
      "seguro medico",
      "health",
      "pharmacy",
      "dentist",
      "\\bsalud\\b",
    ],
  },
  {
    categoria: "Educación",
    palabras: [
      "curso",
      "universidad",
      "matricula",
      "colegio",
      "escuela",
      "academia",
      "clases",
      "\\bmaster\\b",
      "grado",
      "oposicion",
      "udemy",
      "coursera",
      "domestika",
      "skillshare",
      "duolingo",
      "idiomas",
      "guarderia",
      "libros de texto",
      "tutoria",
      "formacion",
      "bootcamp",
      "tuition",
      "school",
      "university",
      "educacion",
      "estudios",
    ],
  },
  {
    categoria: "Alojamiento",
    palabras: [
      "alquiler",
      "hipoteca",
      "comunidad",
      "\\bibi\\b",
      "derrama",
      "portero",
      "ascensor",
      "piso",
      "casa",
      "apartamento",
      "habitacion",
      "studio",
      "flat",
      "rent",
      "mortgage",
      "electricity",
      "electric",
      "luz",
      "agua",
      "calefaccion",
      "caldera",
      "gas natural",
      "hotel",
      "hostal",
      "pension",
      "airbnb",
      "booking",
      "trivago",
      "edreams",
      "lastminute",
      "resort",
      "camping",
      "glamping",
      "balneario",
      "\\balojamiento\\b",
      "\\brenta\\b",
      "vivienda",
      "hospedaje",
    ],
  },
  {
    categoria: "Comida",
    palabras: [
      "mercadona",
      "carrefour",
      "lidl",
      "aldi",
      "dia ",
      "eroski",
      "consum",
      "alcampo",
      "hipercor",
      "bonpreu",
      "condis",
      "coviran",
      "spar",
      "froiz",
      "supercor",
      "supermercado",
      "fruteria",
      "verduleria",
      "carniceria",
      "pescaderia",
      "panaderia",
      "pasteleria",
      "charcuteria",
      "colmado",
      "ultramarinos",
      "alimentacion",
      "grocery",
      "supermarket",
      "glovo",
      "just eat",
      "deliveroo",
      "uber eats",
      "rappi",
      "getir",
      "gorillas",
      "restaurante",
      "restaurant",
      "bar ",
      "cafeteria",
      "cafe ",
      "coffee",
      "starbucks",
      "mcdonalds",
      "mcdonald",
      "burger king",
      "kfc",
      "dominos",
      "telepizza",
      "pizza hut",
      "subway",
      "five guys",
      "popeyes",
      "foster",
      "taco bell",
      "tapas",
      "bocadillo",
      "bocata",
      "menu del dia",
      "cena",
      "almuerzo",
      "desayuno",
      "brunch",
      "sushi",
      "ramen",
      "kebab",
      "hamburgues",
      "poke",
    ],
  },
  {
    categoria: "Transporte",
    palabras: [
      "uber",
      "cabify",
      "bolt",
      "taxi",
      "blablacar",
      "gasolina",
      "gasolinera",
      "repsol",
      "bp ",
      "cepsa",
      "shell",
      "esso",
      "carburante",
      "fuel",
      "metro",
      "bus ",
      "autobus",
      "renfe",
      "ave ",
      "cercanias",
      "fgc",
      "emt ",
      "tmb",
      "tram",
      "bicing",
      "nextbike",
      "voi ",
      "lime ",
      "tier ",
      "peaje",
      "autopista",
      "parking",
      "aparcamiento",
      "garaje",
      "itv",
      "seguro.*coche",
      "coche",
      "moto",
      "ciclomotor",
      "patinete",
      "bicicleta",
      "vueling",
      "iberia",
      "ryanair",
      "easyjet",
      "wizz",
      "air europa",
      "level",
      "transavia",
      "ferry",
      "barco",
      "crucero",
      "aerolinea",
      "flight",
      "avion",
      "\\btren\\b",
      "vuelo",
    ],
  },
  {
    categoria: "Compras",
    palabras: [
      "amazon",
      "ebay",
      "aliexpress",
      "shein",
      "zara",
      "h&m",
      "mango",
      "bershka",
      "stradivarius",
      "pull.*bear",
      "massimo dutti",
      "el corte ingles",
      "primark",
      "lefties",
      "calzedonia",
      "intimissimi",
      "decathlon",
      "nike",
      "adidas",
      "puma",
      "new balance",
      "vans",
      "converse",
      "timberland",
      "zalando",
      "asos",
      "farfetch",
      "vinted",
      "wallapop",
      "fnac",
      "media markt",
      "pc componentes",
      "phone house",
      "apple store",
      "ikea",
      "leroy merlin",
      "aki ",
      "bricomart",
      "bauhaus",
      "worten",
      "ropa",
      "zapatillas",
      "zapatos",
      "vestido",
      "pantalon",
      "camisa",
      "chaqueta",
      "abrigo",
      "complementos",
      "bolso",
      "cartera",
      "reloj",
      "joya",
      "mueble",
      "sofa",
      "cama",
      "colchon",
      "electrodomestico",
      "nevera",
      "lavadora",
      "secadora",
      "microondas",
      "television",
      "movil",
      "ordenador",
      "portatil",
      "tablet",
      "auriculares",
      "altavoz",
      "camara",
      "telmex",
      "totalplay",
      "izzi",
      "megacable",
      "wifi",
      "internet",
      "fibra",
      "router",
      "modem",
      "vodafone",
      "movistar",
      "\\borange\\b",
      "\\bdigi\\b",
      "yoigo",
      "euskaltel",
      "\\bcompras?\\b",
      "tienda",
    ],
  },
  {
    categoria: "Trabajo",
    palabras: [
      "trabajo",
      "oficina",
      "coworking",
    ],
  },
];

/** Reglas ya compiladas, en el mismo orden. */
const COMPILADAS = REGLAS.map((r) => ({
  categoria: r.categoria,
  re: new RegExp(`(${r.palabras.join("|")})`),
}));

/** Devuelve la categoría o null si ninguna palabra coincide. */
export function categoriaPorPalabras(titulo: string): string | null {
  const t = titulo
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");
  for (const r of COMPILADAS) if (r.re.test(t)) return r.categoria;
  return null;
}
